### ISSUE TITLE
add wireframe to google sheets

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/pet-seeker#1]

**Comment by brandonnorsworthy** [comment]
![image](https://user-images.githubusercontent.com/25205589/124335506-23450000-db60-11eb-858f-8ecc48d48375.png)

**Comment by mguppy** [comment]
https://www.figma.com/file/r0pl5xoIOIiw20MmY09eCY/Pet-Seeker?node-id=0%3A1
