### ISSUE TITLE
For past likes, grab small object (name and small picture) by animal ID and get data back when button is clicked in "past likes" pane

### ISSUE THREAD

**Issue by mguppy** [brandonnorsworthy/pet-seeker#40]

**Comment by brandonnorsworthy** [comment]
example of past liked animal array from memory
```javascript
likedPets = [123123,4324234,4324232,234243]
```
you would then use a id and fetch all the data you need
fetch (https://api.petfinder.com/v2/animals/{id})

can use below image doc to get all the information we want to display like an image and the name of the pet as well as give the div that shows the past liked animal a link that redirects to the adoption page
![image](https://user-images.githubusercontent.com/25205589/124830554-ab9c1a00-df3f-11eb-9eb8-e0f5430c5deb.png)

**Comment by brandonnorsworthy** [comment]
Resolved in #65
