### ISSUE TITLE
Connect the preferences to the API call to Pet Finder

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/pet-seeker#44]
![image](https://user-images.githubusercontent.com/25205589/124829332-1cdacd80-df3e-11eb-9020-e697d6025bfb.png)
age, gender, size... 
can just be like 
```
age = document.getElementById("Age").value
```
thereby "linking" the element in the html to the js api call

**Comment by mguppy** [comment]
Updated preferences to be called on submit by users so that the API call only generates the animals that align with the user's preferences
