### ISSUE TITLE
Add a info hover event that shows attributes about a description of animal

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/pet-seeker#5]
![image](https://user-images.githubusercontent.com/25205589/124361643-a7959280-dbf5-11eb-9915-26e49fa66af6.png)

**Comment by brandonnorsworthy** [comment]
https://docs.thedogapi.com/api-reference/breeds/breeds-list

**Comment by mguppy** [comment]
59503b7 - added dog api call

**Comment by mguppy** [comment]
Printed life span, temperament, and weights(converted to US pounds) to the console

**Comment by mguppy** [comment]
Closing as now the life span, temperament, and weights are printing to the tooltip box when you hover over the breed name
